package edu.ncsa.gridshib.gridshibca;
/*
GridShibCAClientView.java

This file is part of the GridShib-CA distribution.

Copyright 2006-2009 The Board of Trustees of the University of Illinois.
Please see LICENSE at the root of the distribution.
*/


import java.awt.Dimension;
import java.awt.Toolkit;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import org.jdesktop.application.ResourceMap;

/**
 * The application's main frame.
 */
public class GridShibCAClientView
        extends FrameView
{

    JFrame mainFrame;
    DebugFrame debugFrame = null;
    CredentialInfoFrame credInfo = null;
    ResourceMap resourceMap;

    public GridShibCAClientView(SingleFrameApplication app)
    {
        super(app);

        initComponents();

        resourceMap = org.jdesktop.application.Application.getInstance(edu.ncsa.gridshib.gridshibca.GridShibCAClientApp.class).getContext().getResourceMap(GridShibCAClientView.class);

        mainFrame = getFrame();

        /* Don't allow resizing */
        mainFrame.setResizable(false);
        
        /* Center our GUI*/
        mainFrame.pack();
        mainFrame.setLocationRelativeTo(null);

        debugFrame = new DebugFrame();
        credInfo = new CredentialInfoFrame();

        showCredInfoMenuItem.setEnabled(false);
        exitButton.setEnabled(false);
    }

    @Action
    public void showAboutBox()
    {
        if (aboutBox == null)
        {
            aboutBox = new GridShibCAClientAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        GridShibCAClientApp.getApplication().show(aboutBox);
    }

    @Action
    public void showDebugFrame()
    {
        if (debugFrame != null)
        {
            debugFrame.setLocationRelativeTo(mainFrame);
            debugFrame.display();
        }
    }

    @Action
    public void showCredentialInfo()
    {
        if (credInfo != null)
        {
            credInfo.setLocationRelativeTo(mainFrame);
            credInfo.display();
        }
    }

    public void setStatus(String message)
    {
        statusLabel.setText(message);
        debugMessage(message);
    }

    public void debugMessage(String message)
    {
        if (debugFrame != null)
        {
            debugFrame.debugMessage(message);
        }
    }

    public void error(String message)
    {
        error(message, null);
    }

    public void error(String message, Exception ex)
    {
        if (ex != null)
        {
            debugFrame.logException(ex);
        }
        ErrorDialog errorDialog = new ErrorDialog(mainFrame, /* modal */ false);
        errorDialog.setDebugFrame(debugFrame);
        errorDialog.display(message);
        errorDialog.display(ex.getMessage());
    }

    public void displayCredentalInfo(Credential cred)
    {
        credInfo.setCredential(cred);
        showCredInfoMenuItem.setEnabled(true);
    }

    public void displaySuccess()
    {
        doneLabel.setIcon(resourceMap.getIcon("doneLabel.icon"));
        doneLabel.setText(resourceMap.getString("doneLabel.successText"));

    }

    public void enableExitButton()
    {
        exitButton.setEnabled(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        javax.swing.JLabel imageLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        doneLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        statusTitleLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        showCredInfoMenuItem = new javax.swing.JMenuItem();
        showDebugMenuItem = new javax.swing.JMenuItem();
        showHelpMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();

        mainPanel.setMaximumSize(new java.awt.Dimension(32767, 300));
        mainPanel.setMinimumSize(new java.awt.Dimension(350, 250));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(350, 250));

        imageLabel.setName("imageLabel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(edu.ncsa.gridshib.gridshibca.GridShibCAClientApp.class).getContext().getActionMap(GridShibCAClientView.class, this);
        exitButton.setAction(actionMap.get("quit")); // NOI18N
        exitButton.setName("exitButton"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edu.ncsa.gridshib.gridshibca.GridShibCAClientApp.class).getContext().getResourceMap(GridShibCAClientView.class);
        doneLabel.setIcon(resourceMap.getIcon("doneLabel.icon")); // NOI18N
        doneLabel.setText(resourceMap.getString("doneLabel.text")); // NOI18N
        doneLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        doneLabel.setDisabledIcon(resourceMap.getIcon("doneLabel.disabledIcon")); // NOI18N
        doneLabel.setEnabled(false);
        doneLabel.setName("doneLabel"); // NOI18N
        doneLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        statusTitleLabel.setFont(resourceMap.getFont("statusTitleLabel.font")); // NOI18N
        statusTitleLabel.setText(resourceMap.getString("statusTitleLabel.text")); // NOI18N
        statusTitleLabel.setName("statusTitleLabel"); // NOI18N

        statusLabel.setText(resourceMap.getString("statusLabel.text")); // NOI18N
        statusLabel.setName("statusLabel"); // NOI18N

        org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanelLayout.createSequentialGroup()
                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(mainPanelLayout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(mainPanelLayout.createSequentialGroup()
                                .add(statusTitleLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(statusLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 191, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(doneLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 317, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(mainPanelLayout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                            .add(exitButton)
                            .add(jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(imageLabel)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanelLayout.createSequentialGroup()
                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(mainPanelLayout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(imageLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(mainPanelLayout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jLabel1)
                        .add(38, 38, 38)
                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, statusTitleLabel)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, statusLabel))
                        .add(18, 18, 18)
                        .add(doneLabel)
                        .add(18, 18, 18)
                        .add(exitButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        showCredInfoMenuItem.setAction(actionMap.get("showCredentialInfo")); // NOI18N
        showCredInfoMenuItem.setText(resourceMap.getString("showCredInfoMenuItem.text")); // NOI18N
        showCredInfoMenuItem.setName("showCredInfoMenuItem"); // NOI18N
        fileMenu.add(showCredInfoMenuItem);

        showDebugMenuItem.setAction(actionMap.get("showDebugFrame")); // NOI18N
        showDebugMenuItem.setText(resourceMap.getString("showDebugMenuItem.text")); // NOI18N
        showDebugMenuItem.setName("showDebugMenuItem"); // NOI18N
        fileMenu.add(showDebugMenuItem);

        showHelpMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        showHelpMenuItem.setText(resourceMap.getString("showHelpMenuItem.text")); // NOI18N
        showHelpMenuItem.setName("showHelpMenuItem"); // NOI18N
        fileMenu.add(showHelpMenuItem);

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel doneLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem showCredInfoMenuItem;
    private javax.swing.JMenuItem showDebugMenuItem;
    private javax.swing.JMenuItem showHelpMenuItem;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusTitleLabel;
    // End of variables declaration//GEN-END:variables
    private JDialog aboutBox;
}
