/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PassphraseDialog.java
 *
 * Created on Nov 22, 2010, 11:48:44 AM
 */

package edu.ncsa.gridshib.gridshibca;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import org.jdesktop.application.Action;

/**
 *
 * @author jbasney
 */
public class PassphraseDialog extends javax.swing.JDialog {

    private static int minPassphraseLength = 12; // IGTF default

    /** Creates new form PassphraseDialog */
    public PassphraseDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        minPassphraseLength =
                GridShibCAProperties.getPropertyAsInt("minPassphraseLength");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        Instructions1 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        Instructions2 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(4, 22, 485, 280));
        setMaximumSize(new java.awt.Dimension(485, 280));
        setMinimumSize(new java.awt.Dimension(485, 280));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 280));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edu.ncsa.gridshib.gridshibca.GridShibCAClientApp.class).getContext().getResourceMap(PassphraseDialog.class);
        Title.setFont(resourceMap.getFont("Title.font")); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText(resourceMap.getString("Title.text")); // NOI18N
        Title.setName("Title"); // NOI18N

        jPasswordField1.setText(resourceMap.getString("jPasswordField1.text")); // NOI18N
        jPasswordField1.setToolTipText(resourceMap.getString("jPasswordField1.toolTipText")); // NOI18N
        jPasswordField1.setName("jPasswordField1"); // NOI18N
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });

        Instructions1.setText(resourceMap.getString("Instructions1.text")); // NOI18N
        Instructions1.setName("Instructions1"); // NOI18N

        jPasswordField2.setText(resourceMap.getString("jPasswordField2.text")); // NOI18N
        jPasswordField2.setToolTipText(resourceMap.getString("jPasswordField2.toolTipText")); // NOI18N
        jPasswordField2.setName("jPasswordField2"); // NOI18N
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyReleased(evt);
            }
        });

        Instructions2.setText(resourceMap.getString("Instructions2.text")); // NOI18N
        Instructions2.setName("Instructions2"); // NOI18N

        statusLabel.setText(resourceMap.getString("statusLabel.text")); // NOI18N
        statusLabel.setName("statusLabel"); // NOI18N

        OK.setText(resourceMap.getString("OK.text")); // NOI18N
        OK.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        OK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OK.setName("OK"); // NOI18N
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(Title, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .add(OK))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(Instructions2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap(20, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(statusLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap(20, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(Instructions1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPasswordField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPasswordField2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(Title)
                .add(18, 18, 18)
                .add(Instructions1)
                .add(10, 10, 10)
                .add(jPasswordField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(Instructions2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPasswordField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(statusLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 17, Short.MAX_VALUE)
                .add(OK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        if (checkPassphrases()) {
            close();
        }
    }//GEN-LAST:event_OKActionPerformed

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        if (checkPassphrases() && evt.getKeyCode() == KeyEvent.VK_ENTER) {
            close();
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jPasswordField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyReleased
        if (checkPassphrases() && evt.getKeyCode() == KeyEvent.VK_ENTER) {
            close();
        }
    }//GEN-LAST:event_jPasswordField2KeyReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PassphraseDialog dialog = new PassphraseDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public boolean checkPassphrases()
    {
        boolean result = false;
        char [] p1 = jPasswordField1.getPassword();
        char [] p2 = jPasswordField2.getPassword();
        if (p1.length < minPassphraseLength) {
            statusLabel.setText("Passphrase is too short. It must be " +
                    minPassphraseLength + " characters or longer.");
        } else if (!Arrays.equals(p1, p2)) {
            statusLabel.setText("Passphrases do not match.");
        } else {
            statusLabel.setText(" ");
            result = true;
        }
        OK.setEnabled(result);
        return result;
    }

    public char [] getPassphrase()
    {
        display();
        if (checkPassphrases()) {
            return jPasswordField1.getPassword();
        }
        return null;
    }

    public void display()
    {
        center();
        OK.setEnabled(false);
        statusLabel.setText(" ");
        Instructions1.setText("Enter a " + minPassphraseLength + " character (or longer) passphrase to protect your private key:");
        setResizable(false);
        setVisible(true);
    }

    @Action
    public void close()
    {
        setVisible(false);
    }

    private void center()
    {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;
        setLocation(x, y);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Instructions1;
    private javax.swing.JLabel Instructions2;
    private javax.swing.JButton OK;
    private javax.swing.JLabel Title;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

}
